#!/bin/bash

# DevSpaces API Token Helper Script
# This script helps you get the OAuth token from OpenShift console

echo "🔐 DevSpaces API Token Helper"
echo "=============================="
echo ""
echo "To get your OAuth Bearer token:"
echo ""
echo "1. Open your browser and go to:"
echo "   https://console-openshift-console.apps.<your-cluster-domain>"
echo ""
echo "2. Login with your credentials:"
echo "   Username: <your-username>"
echo "   Password: <your-password>"
echo ""
echo "3. Once logged in, click on your username in the top-right corner"
echo ""
echo "4. Click 'Copy login command'"
echo ""
echo "5. In the terminal that opens, run the 'oc login' command"
echo ""
echo "6. After successful login, run:"
echo "   oc whoami -t"
echo ""
echo "7. Copy the token that's displayed"
echo ""
echo "8. Use that token with the test_endpoints.py script"
echo ""
echo "Alternative method using curl:"
echo "=============================="
echo ""
echo "You can also get the token directly using curl:"
echo ""
echo "curl -k -u <your-username>:<your-password> \\"
echo "  'https://oauth-openshift.apps.<your-cluster-domain>/oauth/authorize?response_type=token&client_id=openshift-challenging-client' \\"
echo "  -H 'X-CSRF-Token: 1' \\"
echo "  -v 2>&1 | grep -oP 'access_token=\K[^&]*'"
echo ""
echo "Note: The token will be in the Location header of the response"
